### ISSUE TITLE
hoverColor issues

### ISSUE THREAD

**Issue by mcrowder65** [TeamWertarbyte/material-ui-toggle-icon#1]
```
warning.js:33 Warning: Unknown prop `hoverColor` on <svg> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in svg (created by SvgIcon)
    in SvgIcon (created by withStyles(SvgIcon))
    in withStyles(SvgIcon) (created by Clear)
    in Clear (created by pure(Clear))
    in pure(Clear) (created by FileUpload)
    in div (created by ToggleIcon)
    in ToggleIcon (created by FileUpload)
```

I don't believe that hoverColor is a property of an mui-icon, I was able to get rid of this warning upon removing the hoverColor property in the lib/ToggleIcon.js file... lines 103, 108

**Comment by leMaik** [comment]
I think you are using the wrong version. The pre-release `material-ui-toggle-icon@next` is for material-ui 1.0.0-beta, while `material-ui-toggle-icon@latest` is for material-ui 0.x, please update it.

**Comment by mcrowder65** [comment]
I ended up not needing it so I can’t remember which one we were using. Will close the issue

**Comment by zcmgyu** [comment]
`material-ui-toggle-icon@next` works for me. Thanks a lot
