### ISSUE TITLE
Typescript declaration is missing

### ISSUE THREAD

**Issue by alexstrat** [TeamWertarbyte/material-ui-toggle-icon#17]
Because `package.json`'s `typings` property refers to `lib/ToggleIcon.d.ts` but there is no such file in the published package: https://unpkg.com/browse/material-ui-toggle-icon@1.1.1/lib/

**Comment by leMaik** [comment]
PR welcome… It should be changed to reference `src/ToggleIcon.d.ts`

**Comment by leMaik** [comment]
Fixed in v1.1.2
