### ISSUE TITLE
The on/off icons do not switch on toggle in Microsoft Edge 

### ISSUE THREAD

**Issue by conny-nyman** [TeamWertarbyte/material-ui-toggle-icon#7]
If you go to the demo with Microsoft Edge https://mui.wertarbyte.com/#material-ui-toggle-icon
and try to toggle the "Visibility" icon, the icon do not switch to "VisibilityOff". 

Are you planning to add support for Microsoft Edge?

**Comment by leMaik** [comment]
Looks like Edge only supports the property in SVGs, see https://stackoverflow.com/a/40943890. Maybe we could detect Edge and just switch the icon without an animation? A PR would be welcome, as long as the code for that is reasonably short. :+1: 

Good that Microsoft finally gave up trying to develop a good Web engine and [will use Chromium in the future](https://www.theverge.com/2018/12/6/18128648/microsoft-edge-chrome-chromium-browser-changes) :roll_eyes:

**Comment by conny-nyman** [comment]
I was about to start working on a fix for this issue today, but apparently the toggle icon works on edge on my home computer. 

Edge version I tested with
![MUI-toggle-icon-edge-working](https://user-images.githubusercontent.com/25151529/54489300-81784700-48b3-11e9-93b0-127866201d77.PNG)

I have to see what version of Edge is installed on my work computer and see if it is running an older version of Edge, perhaps this issue can be fixed just by updating Edge!

**Comment by leMaik** [comment]
A solution using the `clip` CSS property might be possible. It's deprecated, but it works in all browsers.

**Comment by conny-nyman** [comment]
Opened PR #8
