### ISSUE TITLE
React concurrent mode throws this error

### ISSUE THREAD

**Issue by NawarA** [TeamWertarbyte/material-ui-toggle-icon#9]
`Expected ref to be a function, a string, an object returned by React.createRef(), or null.`

I believe its coming `React.cloneElement`

**Comment by leMaik** [comment]
we don't use refs in our code, so I guess it's an issue in your code.

**Comment by NawarA** [comment]
My bad. I was passing a reference to the SVG Icon, instead of an instantiated icon, so the React.cloneElement was throwing. Looks good in Concurrent mode actually!

Btw, love the library. Would love to see this added MUI's official code base, as everyone should use your lib

**Comment by leMaik** [comment]
@NawarA I'm not sure if this component would be approved into Material-UI. It usually depends on demand, e.g. many people needed a rating component so one was included in Material-UI (although there were some community components).

**Comment by NawarA** [comment]
There is an [open issue ](https://github.com/mui-org/material-ui/issues/12639) and feature request to add simple animations to material design. Your lib is the start of that :)
